### ISSUE TITLE
What happened to the old builds?

### ISSUE THREAD

**Issue by sled45** [Jazzzny/jdk-macos-legacy#2]
I saw the post on the MacRumors Forums about legacy JDK, and it said you can download it from the releases here, but there aren't any. I saw that on the Wayback Machine it shows there were at some point releases, is there a reason for this? Sorry if this comes off as rude, I was just wondering.

**Comment by sled45** [comment]
Didn't notice the repository with the old builds, sorry.

**Comment by Jazzzny** [comment]
Hey there, I've cloned the repository as I'm in the process of rebuilding all of the releases. I haven't had much time recently, but it should hopefully be done by the end of the month.
